'datadir' : "/home/cohen/lsst/photoz/sedfitting/SPEC/edmond_lib/raw_sed/edmond_public_html_spectra/"
'workdir' : '.'
'fors2catalog' : '/home/cohen/lsst/photoz/sedfitting/fors2/data/fors2_catalogue.fits'